{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "count", "label": "count", "query": "5, 10, 20" },
   { "name": "duration", "label": "duration", "query": "30m, 12h, 1d, 7d, 30d" }
  ]
 },
 "panels": [
  { "title": "CPU/Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "kubevirt_vmi_vcpu_seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, max_over_time((avg(rate(kubevirt_vmi_vcpu_seconds[5m])) by (domain, name))[${duration}:])) "
    }
   ]
  },
  {
   "title": "kubevirt_vmi_memory_resident_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, max_over_time((kubevirt_vmi_memory_resident_bytes)[${duration}:]))"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "kubevirt_vmi_storage_read_traffic_bytes_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, max_over_time((sum(irate(kubevirt_vmi_storage_read_traffic_bytes_total[5m])) by (name, namespace))[${duration}:])) "
    }
   ]
  },
  {
   "title": "kubevirt_vmi_storage_write_traffic_bytes_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, max_over_time((sum(irate(kubevirt_vmi_storage_write_traffic_bytes_total[5m])) by (name, namespace))[${duration}:])) "
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "kubevirt_vmi_network_receive_bytes_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, max_over_time((sum(irate(kubevirt_vmi_network_receive_bytes_total[5m])*8) by (name, namespace, interface))[${duration}:]))"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_network_transmit_bytes_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, max_over_time((sum(irate(kubevirt_vmi_network_transmit_bytes_total[5m])*8) by (name, namespace, interface))[${duration}:]))"
    }
   ]
  }
 ]
}