{
 "title": "KubeVirt VM Info",
 "description": "KubeVirt VM Info",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kubevirt_vmi_vcpu_seconds, namespace)"
   },
   {
    "name": "vm",
    "label": "vm",
    "query": "label_values(kubevirt_vmi_vcpu_seconds{namespace=\"$namespace\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "vm Pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kubevirt_vmi_phase_count", "legendFormat": "{{phase}}" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "kubevirt_vmi_memory_usable_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_usable_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_memory_used_total_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_used_total_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_memory_swap_in_traffic_bytes_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_swap_in_traffic_bytes_total{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_memory_swap_out_traffic_bytes_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_swap_out_traffic_bytes_total{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_memory_pgmajfault",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_memory_pgmajfault{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_memory_pgminfault",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_memory_pgminfault{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_memory_available_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_available_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_memory_resident_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_resident_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_memory_unused_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_unused_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_memory_actual_balloon_bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_actual_balloon_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  { "title": "CPU/Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(kubevirt_vmi_vcpu_seconds{namespace=\"$namespace\", name=\"$vm\"}[5m])) by (domain, name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubevirt_vmi_memory_resident_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "kubevirt_vmi_storage_flush_requests_total",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubevirt_vmi_storage_flush_requests_total{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "{{drive}}-{{type}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_storage_flush_times_ms_total",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "conmgdL" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kubevirt_vmi_storage_flush_times_ms_total{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "{{drive}}-{{type}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_storage_iops_write_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_iops_write_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_storage_write_traffic_bytes_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_write_traffic_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_storage_write_times_ms_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_write_times_ms_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-{{type}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_storage_iops_read_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_iops_read_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_storage_read_traffic_bytes_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_read_traffic_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_storage_read_times_ms_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_read_times_ms_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-{{type}}"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "kubevirt_vmi_network_receive_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_receive_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_network_transmit_bytes_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_transmit_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_network_receive_errors_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_receive_errors_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_network_transmit_errors_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_transmit_errors_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_network_receive_packets_dropped_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_receive_packets_dropped_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_network_transmit_packets_dropped_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_transmit_packets_dropped_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_network_receive_packets_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_receive_packets_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  },
  {
   "title": "kubevirt_vmi_network_transmit_packets_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_transmit_packets_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-{{type}}"
    }
   ]
  }
 ]
}