apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "logging-operator.fullname" . }}
  labels:
{{ include "logging-operator.labels" . | indent 4 }}
data:
{{ (.Files.Glob "crds/*.yaml").AsConfig | indent 2 }}
