apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "logging-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: {{ template "logging-operator.fullname" . }}
      securityContext:
        runAsUser: 65534
        runAsNonRoot: true
        fsGroup: 65534
      containers:
      - name: operator-init-crds
        image: rancher/istio-kubectl:1.5.10
        volumeMounts:
        - name: data-crds
          mountPath: /etc/operator-init
          readOnly: true
        command: ["kubectl",  "apply", "-f", "/etc/operator-init/."]
      volumes:
      - name: data-crds
        configMap:
          name: {{ template "logging-operator.fullname" . }}
      restartPolicy: Never
