apiVersion: v1
description: Provides monitoring for Kubernetes which is maintained by Rancher 2.
engine: gotpl
name: harvester-monitoring
version: 0.1.0
appVersion: 0.1.0
kubeVersion: ">=1.16.0-0"
home: https://github.com/coreos/prometheus-operator
keywords:
- operator
- prometheus
icon: https://coreos.com/sites/default/files/inline-images/Overview-prometheus_0.png
