operator:
  nameOverride: "prometheus-operator"
  enabledRBAC: true
  apiGroup: "monitoring.coreos.com"
  image:
    repository: rancher/coreos-prometheus-operator
    tag: v0.39.0
    prometheusConfigReloader:
      repository: rancher/coreos-prometheus-config-reloader
      tag: v0.39.0
    configmapReload:
      repository: rancher/jimmidyson-configmap-reload
      tag: v0.3.0
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  nodeSelectors: []
  tolerations: []
  logFormat: "logfmt"
  logLevel: "info"
  serviceAccountName: ""

grafana:
  enabled: false
  level: cluster
  apiGroup: "monitoring.coreos.com"
  image:
    repository: rancher/grafana-grafana
    tag: 7.1.5
    tool:
      repository: rancher/prometheus-auth
      tag: v0.2.1
    proxy:
      repository: rancher/mirrored-library-nginx
      tag: 1.19.9-alpine
  nodeSelectors: []
  resources:
    inits:
      limits:
        memory: 50Mi
        cpu: 50m
      requests:
        memory: 50Mi
        cpu: 50m
    core:
      limits:
        memory: 200Mi
        cpu: 200m
      requests:
        memory: 100Mi
        cpu: 100m
    proxy:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 50m
  persistence:
    name: ""
    enabled: false
    storageClass: ""
    accessMode: "ReadWriteOnce"
    size: 50Gi
  ## Already exist ServiceAccount
  ##
  serviceAccountName: ""
  prometheusDatasourceURL: "http://prometheus-operated:9090"
  livenessProbe: {}
  readinessProbe: {}

prometheus:
  enabled: false
  level: cluster
  apiGroup: "monitoring.coreos.com"
  image:
    repository: rancher/prom-prometheus
    tag: v2.18.2
    proxy:
      repository: rancher/mirrored-library-nginx
      tag: 1.19.9-alpine
  nodeSelectors: []
  resources:
    core:
      limits:
        memory: 500Mi
        cpu: 1000m
      requests:
        memory: 100Mi
        cpu: 100m
    proxy:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 50Mi
        cpu: 50m
  persistence:
    name: ""
    enabled: false
    storageClass: ""
    accessMode: "ReadWriteOnce"
    size: 50Gi
  alertingEndpoints: []
  secrets: []
  ## Override the default generated ServiceAccount name
  ##
  serviceAccountNameOverride: ""
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchExpressions: []
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    fsGroup: 2000
  sync:
    mode: "remote"
    path: "/api/v1/read"
    target: ""
  project:
    alertManagerTarget: ""
    projectDisplayName: ""
    clusterDisplayName: ""
  cluster:
    alertManagerNamespace: ""
  livenessProbe: {}
  readinessProbe: {}

operator-init:
  enabled: false
  apiGroup: "monitoring.coreos.com"
  image:
    repository: rancher/kubectl
    tag: v1.18.6
  resources:
    limits:
      cpu: 20m
      memory: 50Mi
    requests:
      cpu: 20m
      memory: 20Mi
